export const MACRO_MESO_MAP: Record<string, { code: string; label?: string }[]> = {
  BRAD: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'ITIP' },
  ],
  CHXO: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
    { code: 'FMCD' },
  ],
  CONF: [
    { code: 'BARS' }, 
    { code: 'POOL' }, 
    { code: 'CHNB' }, 
    { code: 'TLWG' },
],
  DEND: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'ITIP' },
  ],
  DRNG: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'ITIP' },
  ],
  DTWT: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
  ],
  FDPN: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
  ],
  FTBW: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
  ],
  ISB: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'FMCD' },
  ],
  OSB: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
    { code: 'FMCD' },
  ],
  SCCL: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
    { code: 'ITIP' },
  ],
  SCCS: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
    { code: 'ITIP' },
  ],
  SCN: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
  ],
  TRIB: [],
  TRML: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
  ],
  TRMS: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
  ],
  WILD: [
    { code: 'BARS' },
    { code: 'POOL' },
    { code: 'CHNB' },
    { code: 'TLWG' },
    { code: 'OTHE' },
  ],
};
