# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TEST CI

name: CI Build User Interface

on:
  push:
    branches:
      - develop
jobs:
  build:
    env:
      PUBLIC_URL: https://develop-pallid-sturgeon.rsgis.dev
      REACT_APP_API_URL: https://develop-pallid-sturgeon-api.rsgis.dev
      REACT_APP_KEYCLOAK_URL: https://auth-test.sec.usace.army.mil/auth
      REACT_APP_REDIRECT_URL: https://develop-pallid-sturgeon.rsgis.dev
      REACT_APP_KEYCLOAK_REALM: CWBI-DEV
      REACT_APP_KEYCLOAK_CLIENT: pallid-sturgeon-dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

      - name: Deploy to Dev
        env:
          AWS_DEFAULT_REGION: ${{ secrets.CWBICI_DEVELOP_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CWBICI_DEVELOP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CWBICI_DEVELOP_AWS_SECRET_ACCESS_KEY }}
        run: npm run deploy-develop
